[bufferline]
fetch.github = "akinsho/bufferline.nvim"
src.git = "https://github.com/akinsho/bufferline.nvim"

[catppuccin]
fetch.github = "catppuccin/nvim"
passthru.as = "catppuccin"
src.git = "https://github.com/catppuccin/nvim"

[cloak]
fetch.github = "laytan/cloak.nvim"
src.git = "https://github.com/laytan/cloak.nvim"

[copilot-lua]
fetch.github = "zbirenbaum/copilot.lua"
src.git = "https://github.com/zbirenbaum/copilot.lua"

[crates]
fetch.github = "saecki/crates.nvim"
src.git = "https://github.com/saecki/crates.nvim"

[cuddlefish]
fetch.github = "comfysage/cuddlefish.nvim"
src.git = "https://github.com/comfysage/cuddlefish.nvim"

[direnv]
fetch.github = "NotAShelf/direnv.nvim"
src.git = "https://github.com/NotAShelf/direnv.nvim"

[evergarden]
fetch.github = "comfysage/evergarden"
src.git = "https://github.com/comfysage/evergarden"

[fidget]
fetch.github = "j-hui/fidget.nvim"
src.git = "https://github.com/j-hui/fidget.nvim"

[formatter-nvim]
fetch.github = "mhartington/formatter.nvim"
src.git = "https://github.com/mhartington/formatter.nvim"

[freeze]
fetch.github = "charm-community/freeze.nvim"
src.git = "https://github.com/charm-community/freeze.nvim"

[gitsigns]
fetch.github = "lewis6991/gitsigns.nvim"
src.git = "https://github.com/lewis6991/gitsigns.nvim"

[harpoon]
fetch.github = "ThePrimeagen/harpoon"
src.branch = "harpoon2"
src.git = "https://github.com/ThePrimeagen/harpoon"

[img-clip-nvim]
fetch.github = "HakonHarnes/img-clip.nvim"
src.git = "https://github.com/HakonHarnes/img-clip.nvim"

[indent-blankline]
fetch.github = "lukas-reineke/indent-blankline.nvim"
src.git = "https://github.com/lukas-reineke/indent-blankline.nvim"

[lazydev]
fetch.github = "folke/lazydev.nvim"
src.git = "https://github.com/folke/lazydev.nvim"

[lsp-status]
fetch.github = "nvim-lua/lsp-status.nvim"
src.git = "https://github.com/nvim-lua/lsp-status.nvim"

[lualine]
fetch.github = "nvim-lualine/lualine.nvim"
src.git = "https://github.com/nvim-lualine/lualine.nvim"

[lz-n]
fetch.github = "nvim-neorocks/lz.n"
passthru.start = "true"
src.git = "https://github.com/nvim-neorocks/lz.n"

[lzn-auto-require]
fetch.github = "horriblename/lzn-auto-require"
passthru.start = "true"
src.git = "https://github.com/horriblename/lzn-auto-require"

[markview]
fetch.github = "OXY2DEV/markview.nvim"
src.git = "https://github.com/OXY2DEV/markview.nvim"

[mini-icons]
fetch.github = "echasnovski/mini.icons"
src.git = "https://github.com/echasnovski/mini.icons"

[mini-surround]
fetch.github = "echasnovski/mini.surround"
src.git = "https://github.com/echasnovski/mini.surround"

[neo-tree]
fetch.github = "nvim-neo-tree/neo-tree.nvim"
src.git = "https://github.com/nvim-neo-tree/neo-tree.nvim"

[neovim-session-manager]
fetch.github = "Shatur/neovim-session-manager"
src.git = "https://github.com/Shatur/neovim-session-manager"

[nvim-colorizer]
fetch.github = "nvchad/nvim-colorizer.lua"
src.git = "https://github.com/nvchad/nvim-colorizer.lua"

[nvim-lspconfig]
fetch.github = "neovim/nvim-lspconfig"
passthru.start = "true"
src.git = "https://github.com/neovim/nvim-lspconfig"

[nvim-lint]
fetch.github = "mfussenegger/nvim-lint"
src.git = "https://github.com/mfussenegger/nvim-lint"

[nvim-navic]
fetch.github = "SmiteshP/nvim-navic"
src.git = "https://github.com/SmiteshP/nvim-navic"

[nvim-treesitter]
fetch.github = "nvim-treesitter/nvim-treesitter"
passthru.start = "true"
src.branch = "main"
src.git = "https://github.com/nvim-treesitter/nvim-treesitter"

[nui]
fetch.github = "MunifTanjim/nui.nvim"
src.git = "https://github.com/MunifTanjim/nui.nvim"

[obsidian-nvim]
fetch.github = "obsidian-nvim/obsidian.nvim"
src.git = "https://github.com/obsidian-nvim/obsidian.nvim"

[plenary]
fetch.github = "nvim-lua/plenary.nvim"
passthru.start = "true"
src.git = "https://github.com/nvim-lua/plenary.nvim"

[quill-nvim]
fetch.github = "comfysage/quill.nvim"
src.git = "https://github.com/comfysage/quill.nvim"

[rainbow-delimiters]
fetch.github = "hiphish/rainbow-delimiters.nvim"
src.git = "https://github.com/hiphish/rainbow-delimiters.nvim"

[rustaceanvim]
fetch.github = "mrcjkb/rustaceanvim"
src.git = "https://github.com/mrcjkb/rustaceanvim"

[sayama-nvim]
fetch.github = "comfysage/sayama.nvim"
src.git = "https://github.com/comfysage/sayama.nvim"

[schemastore]
fetch.github = "b0o/schemastore.nvim"
src.git = "https://github.com/b0o/schemastore.nvim"

[snacks-nvim]
fetch.github = "folke/snacks.nvim"
src.git = "https://github.com/folke/snacks.nvim"

[todo-comments]
fetch.github = "folke/todo-comments.nvim"
src.git = "https://github.com/folke/todo-comments.nvim"

[toggleterm]
fetch.github = "akinsho/toggleterm.nvim"
src.git = "https://github.com/akinsho/toggleterm.nvim"

[trouble]
fetch.github = "folke/trouble.nvim"
src.git = "https://github.com/folke/trouble.nvim"

[undotree]
fetch.github = "jiaoshijie/undotree"
src.git = "https://github.com/jiaoshijie/undotree"

[vim-fugitive]
fetch.github = "tpope/vim-fugitive"
src.git = "https://github.com/tpope/vim-fugitive"

[wakatime]
fetch.github = "wakatime/vim-wakatime"
src.git = "https://github.com/wakatime/vim-wakatime"

[fzf-lua]
fetch.github = "ibhagwan/fzf-lua"
src.git = "https://github.com/ibhagwan/fzf-lua"
