# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha-nvim = {
    pname = "alpha-nvim";
    version = "41283fb402713fc8b327e60907f74e46166f4cfd";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "41283fb402713fc8b327e60907f74e46166f4cfd";
      fetchSubmodules = false;
      sha256 = "sha256-kTVPKZ/e1us/uHfSwFwR38lFYN8EotJq2jKz6xm/eqg=";
    };
    date = "2024-02-25";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "0b5df9c9e641b1212b21a0762ccad4434fd41322";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "0b5df9c9e641b1212b21a0762ccad4434fd41322";
      fetchSubmodules = false;
      sha256 = "sha256-JhKJQDdHiiDcCtbc8xvdLa6W5oRBDcftM+G5aVEMi6Q=";
    };
    date = "2024-07-18";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "d250c63aa13ead745e3a40f61fdd3470efde3923";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "d250c63aa13ead745e3a40f61fdd3470efde3923";
      fetchSubmodules = false;
      sha256 = "sha256-iBmXp+gUSMbgfkv7c7RDQAwPq02e07wEnBETP0dWBOo=";
    };
    date = "2024-03-22";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "39e2eda76828d88b773cc27a3f61d2ad782c922d";
      fetchSubmodules = false;
      sha256 = "sha256-CT1+Z4XJBVsl/RqvJeGmyitD6x7So0ylXvvef5jh7I8=";
    };
    date = "2024-05-17";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp_luasnip = {
    pname = "cmp_luasnip";
    version = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
      fetchSubmodules = false;
      sha256 = "sha256-nUJJl2zyK/oSwz5RzI9j3gf9zpDfCImCYbPbVsyXgz8=";
    };
    date = "2023-10-09";
  };
  copilot-cmp = {
    pname = "copilot-cmp";
    version = "b6e5286b3d74b04256d0a7e3bd2908eabec34b44";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot-cmp";
      rev = "b6e5286b3d74b04256d0a7e3bd2908eabec34b44";
      fetchSubmodules = false;
      sha256 = "sha256-8w9go2SBkI+BrXNadWM8ZxDDfrAnZZJx6RbVHAK4+Pg=";
    };
    date = "2024-06-16";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "86537b286f18783f8b67bccd78a4ef4345679625";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "86537b286f18783f8b67bccd78a4ef4345679625";
      fetchSubmodules = false;
      sha256 = "sha256-HC1QZlqEg+RBz/8kjLadafc06UoMAjhh0UO/BWQGMY8=";
    };
    date = "2024-06-14";
  };
  crates = {
    pname = "crates";
    version = "c3fd47391de6999f4c939af89494d08443f71916";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "c3fd47391de6999f4c939af89494d08443f71916";
      fetchSubmodules = false;
      sha256 = "sha256-y1NLR4w7kGVJO5gGSguQB5BpDYrUgyPz/4Tf01c9hG8=";
    };
    date = "2024-07-01";
  };
  editorconfig = {
    pname = "editorconfig";
    version = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
    src = fetchFromGitHub {
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
      fetchSubmodules = false;
      sha256 = "sha256-pR57tITdVGF4luEmmRYv/XFb35E3KDfcgYRijkPAc+Y=";
    };
    date = "2023-01-10";
  };
  evergarden = {
    pname = "evergarden";
    version = "7e031b62f13d8b13eed5a2906d6bf4ea6d44759c";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "7e031b62f13d8b13eed5a2906d6bf4ea6d44759c";
      fetchSubmodules = false;
      sha256 = "sha256-IfV+Y58vkFigucrWbyHsv5y8/QHDndD5DuxmjqRmBvY=";
    };
    date = "2024-07-15";
  };
  fidget = {
    pname = "fidget";
    version = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2f7c08f45639a64a5c0abcf67321d52c3f499ae6";
      fetchSubmodules = false;
      sha256 = "sha256-8Gl2Ck4YJGReSEq1Xeh1dpdRq4eImmrxvIHrfxdem3Q=";
    };
    date = "2023-11-09";
  };
  freeze-nvim = {
    pname = "freeze-nvim";
    version = "402886e9be0025b7b8cbf62392cad89bd0c312ed";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "402886e9be0025b7b8cbf62392cad89bd0c312ed";
      fetchSubmodules = false;
      sha256 = "sha256-KY+JXP6EcztlGJBJDDo133Iohqw6nZSl61OK6Z7JNqI=";
    };
    date = "2024-07-04";
  };
  go-nvim = {
    pname = "go-nvim";
    version = "033344ddfa3cd5cfd55037903264b2bb86691619";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "go.nvim";
      rev = "033344ddfa3cd5cfd55037903264b2bb86691619";
      fetchSubmodules = false;
      sha256 = "sha256-gxW+kE42zlDjeYojh7xWO2S3AntWDCMQjlQMPlMyKJY=";
    };
    date = "2024-07-16";
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "225db770e36aae6a1e9e3a65578095c8eb4038d3";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "225db770e36aae6a1e9e3a65578095c8eb4038d3";
      fetchSubmodules = false;
      sha256 = "sha256-V5rlORFlhgjAT0n+LcpMNdY+rEqQpur/KGTGH6uFxMY=";
    };
    date = "2024-06-05";
  };
  harpoon = {
    pname = "harpoon";
    version = "0378a6c428a0bed6a2781d459d7943843f374bce";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "0378a6c428a0bed6a2781d459d7943843f374bce";
      fetchSubmodules = false;
      sha256 = "sha256-FZQH38E02HuRPIPAog/nWM55FuBxKp8AyrEldFkoLYk=";
    };
    date = "2024-04-09";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "65e20ab94a26d0e14acac5049b8641336819dfc7";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "65e20ab94a26d0e14acac5049b8641336819dfc7";
      fetchSubmodules = false;
      sha256 = "sha256-PSsXBB2KOFPJJ1O8fpTvsVe2A0/wU6Ae9dN/UemraZM=";
    };
    date = "2024-06-28";
  };
  lazy = {
    pname = "lazy";
    version = "9a374a0fb4d3ac42dac4a129d4bead7252473c77";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "9a374a0fb4d3ac42dac4a129d4bead7252473c77";
      fetchSubmodules = false;
      sha256 = "sha256-fRhvF/tnvZSvE2/OeLButsRAeVPBxb6wY6QRY3Zrgrc=";
    };
    date = "2024-07-19";
  };
  lazygit = {
    pname = "lazygit";
    version = "dc56df433bfbf107fee0139e187eb9750878fa84";
    src = fetchFromGitHub {
      owner = "kdheepak";
      repo = "lazygit.nvim";
      rev = "dc56df433bfbf107fee0139e187eb9750878fa84";
      fetchSubmodules = false;
      sha256 = "sha256-BnuFi8TKDsypQ11j2ORJ1JFsFsvAaPtDWm+R7UnIa3M=";
    };
    date = "2024-07-08";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "1735dd5a5054c1fb7feaf8e8658dbab925f4f0cf";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "1735dd5a5054c1fb7feaf8e8658dbab925f4f0cf";
      fetchSubmodules = false;
      sha256 = "sha256-/QLdBU/Zwmkw1NGuLBD48tvrmIP9d9WHhgcLEQgRTWo=";
    };
    date = "2024-01-11";
  };
  ltex-extra = {
    pname = "ltex-extra";
    version = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex-extra.nvim";
      rev = "24acd044ce7a26b3cdb537cbd094de37c3e1ac45";
      fetchSubmodules = false;
      sha256 = "sha256-OGeeEIF+z03DdJO2d2kzQ0lZnIYLabp6irYPqYgbCbc=";
    };
    date = "2024-06-15";
  };
  lualine = {
    pname = "lualine";
    version = "544dd1583f9bb27b393f598475c89809c4d5e86b";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "544dd1583f9bb27b393f598475c89809c4d5e86b";
      fetchSubmodules = false;
      sha256 = "sha256-uNDRynWs7fXDDzDFKvE31oDetv3aabiJfr/r/84z9Sg=";
    };
    date = "2024-07-15";
  };
  luasnip = {
    pname = "luasnip";
    version = "ce0a05ab4e2839e1c48d072c5236cce846a387bc";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "ce0a05ab4e2839e1c48d072c5236cce846a387bc";
      fetchSubmodules = false;
      sha256 = "sha256-zjefbPMiKxwYsBzE75jQRVNFMDSnCq1hKe1cBBqMRWg=";
    };
    date = "2024-06-28";
  };
  neodev = {
    pname = "neodev";
    version = "46aa467dca16cf3dfe27098042402066d2ae242d";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neodev.nvim";
      rev = "46aa467dca16cf3dfe27098042402066d2ae242d";
      fetchSubmodules = false;
      sha256 = "sha256-hOjzlo/IqmV8tYjGwfmcCPEmHYsWnEIwtHZdhpwA1kM=";
    };
    date = "2024-07-06";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "35c154a4b904cbe2aa7acce00a8c1c54a8831780";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "35c154a4b904cbe2aa7acce00a8c1c54a8831780";
      fetchSubmodules = false;
      sha256 = "sha256-RVQf0swrX9SQz7KeuOpWkmBdZwIrVbc112ZXqkElxew=";
    };
    date = "2024-07-15";
  };
  null-ls = {
    pname = "null-ls";
    version = "4c6605b2ec5dfe4c9694ade0c730c234d1039019";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "4c6605b2ec5dfe4c9694ade0c730c234d1039019";
      fetchSubmodules = false;
      sha256 = "sha256-Y0YxPuYWPqzP4PIoVwReh7+RGIDWgkf8WdeG7qpPgWI=";
    };
    date = "2024-07-19";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "d818fd0624205b34e14888358037fb6f5dc51234";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "d818fd0624205b34e14888358037fb6f5dc51234";
      fetchSubmodules = false;
      sha256 = "sha256-jc4fQBaAuL4XhHljVU3sdaEyQCnHbI+gwNOTnGHk0qM=";
    };
    date = "2024-07-16";
  };
  nvim-colorizer-lua = {
    pname = "nvim-colorizer-lua";
    version = "08bd34bf0ed79723f62764c7f9ca70516d461d0d";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "08bd34bf0ed79723f62764c7f9ca70516d461d0d";
      fetchSubmodules = false;
      sha256 = "sha256-3cyf0YFNWuSsrKlFbxoE4vl0t8q4ra85rlxpaqu9UIc=";
    };
    date = "2024-07-16";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "e26da408cf955afa8e9ddbadd510e84ea8976cd7";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "e26da408cf955afa8e9ddbadd510e84ea8976cd7";
      fetchSubmodules = false;
      sha256 = "sha256-GscyvR1SYGUig7GGLDS5xS5weVi32WJuFOypVaZc044=";
    };
    date = "2024-07-19";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "8649f694d3e76ee10c19255dece6411c29206a54";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "8649f694d3e76ee10c19255dece6411c29206a54";
      fetchSubmodules = false;
      sha256 = "sha256-0p5n/V8Jlj9XyxV/fuMwsbQ7oV5m9H2GqZZEA/njxCQ=";
    };
    date = "2023-11-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "d333b6f167900f6d9d42a59005d82919830626bf";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "d333b6f167900f6d9d42a59005d82919830626bf";
      fetchSubmodules = false;
      sha256 = "sha256-wxyHwL/uFdp6w32CVHgSOWkzRrIRuFvWh+J2401RAAA=";
    };
    date = "2024-05-17";
  };
  nvim-tree-lua = {
    pname = "nvim-tree-lua";
    version = "f9ff00bc06d7cb70548a3847d7a2a05e928bc988";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "f9ff00bc06d7cb70548a3847d7a2a05e928bc988";
      fetchSubmodules = false;
      sha256 = "sha256-0p6kz1/LZoIPRMmwpBjq/diP5fia4viQajuxQSHUe4M=";
    };
    date = "2024-07-11";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "0ffe62722307f6755d2c7049837cb2cd6d7d275a";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "0ffe62722307f6755d2c7049837cb2cd6d7d275a";
      fetchSubmodules = false;
      sha256 = "sha256-BXZLzV/NZYh3O+svLpXzaueqpKv35pa2wdcZa1qT6h8=";
    };
    date = "2024-07-19";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "c0cfc1738361b5da1cd0a962dd6f774cc444f856";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "c0cfc1738361b5da1cd0a962dd6f774cc444f856";
      fetchSubmodules = false;
      sha256 = "sha256-j/B/E1VltJ/QpVFtDKAdVC4+KZ5Mz8dQP5kd8HIHjLs=";
    };
    date = "2024-06-09";
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "ee298fd2136612a4ca6a745a4aec3f49ce6f94b0";
    src = fetchFromGitHub {
      owner = "epwalsh";
      repo = "obsidian.nvim";
      rev = "ee298fd2136612a4ca6a745a4aec3f49ce6f94b0";
      fetchSubmodules = false;
      sha256 = "sha256-7xAJV81UqF8KCXwZcg5bncIYzFJ8Hsu5HY5RajoyIIs=";
    };
    date = "2024-07-17";
  };
  plenary = {
    pname = "plenary";
    version = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "a3e3bc82a3f95c5ed0d7201546d5d2c19b20d683";
      fetchSubmodules = false;
      sha256 = "sha256-5Jf2mWFVDofXBcXLbMa417mqlEPWLA+cQIZH/vNEV1g=";
    };
    date = "2024-05-20";
  };
  presence = {
    pname = "presence";
    version = "87c857a56b7703f976d3a5ef15967d80508df6e6";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "87c857a56b7703f976d3a5ef15967d80508df6e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZpsunLsn//zYgUtmAm5FqKVueVd/Pa1r55ZDqxCimBk=";
    };
    date = "2023-01-29";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "278db39aedd697613851861b5ea8b0d9138fc06f";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "278db39aedd697613851861b5ea8b0d9138fc06f";
      fetchSubmodules = false;
      sha256 = "sha256-cNvh7A091kdeLoaoz2ysWuNV0BqzTXgjntU/pDZS92U=";
    };
    date = "2024-02-15";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "b29da4a6061a88270e875b38367d82c04c856128";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "b29da4a6061a88270e875b38367d82c04c856128";
      fetchSubmodules = false;
      sha256 = "sha256-6+MSV9pkudhf/xVdofU6syYCzViHltvDWkYvbeuEfLs=";
    };
    date = "2024-07-07";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "047f9c9d8cd2861745eb9de6c1570ee0875aa795";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "047f9c9d8cd2861745eb9de6c1570ee0875aa795";
      fetchSubmodules = false;
      sha256 = "sha256-Mx8pB9ECjFpbfmZPuXfpwoE5pUZ363M53f27ht7MBmA=";
    };
    date = "2024-07-10";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "58a965eedbfe7c358938b0e535ed2d98a4520987";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "58a965eedbfe7c358938b0e535ed2d98a4520987";
      fetchSubmodules = false;
      sha256 = "sha256-jS13dXMliCjYNgMVxOJc9Z2bItG6GyzECTYjk63+j7U=";
    };
    date = "2024-07-18";
  };
  telescope = {
    pname = "telescope";
    version = "bfcc7d5c6f12209139f175e6123a7b7de6d9c18a";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "bfcc7d5c6f12209139f175e6123a7b7de6d9c18a";
      fetchSubmodules = false;
      sha256 = "sha256-U6fgii9FlJy+bHAtYVnZEOyiUAqlBHTvMFc4mo+xS/s=";
    };
    date = "2024-07-01";
  };
  telescope-file-browser = {
    pname = "telescope-file-browser";
    version = "a7ab9a957b17199183388c6f357d614fcaa508e5";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "a7ab9a957b17199183388c6f357d614fcaa508e5";
      fetchSubmodules = false;
      sha256 = "sha256-2ZXjp0Kzr2Xp7/BjiWBUi2lq6uS80Ada/pXLqxeBfDw=";
    };
    date = "2024-06-09";
  };
  telescope-project = {
    pname = "telescope-project";
    version = "1aaf16580a614601a7f7077d9639aeb457dc5559";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "1aaf16580a614601a7f7077d9639aeb457dc5559";
      fetchSubmodules = false;
      sha256 = "sha256-touMCltcnqkrQYV1NtNeWLQeFVGt+WM3aIWIdKilA7w=";
    };
    date = "2023-12-01";
  };
  telescope-ui-select = {
    pname = "telescope-ui-select";
    version = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
      fetchSubmodules = false;
      sha256 = "sha256-YRhNmmG4gx9Ht8JwjQfbTjJyTHEuZmtP6lqnhOsk8bE=";
    };
    date = "2023-12-04";
  };
  tiny-devicons-auto-colors-nvim = {
    pname = "tiny-devicons-auto-colors-nvim";
    version = "9be4af5b1bc1f26a11206ed7ce8bf44312e7941a";
    src = fetchFromGitHub {
      owner = "rachartier";
      repo = "tiny-devicons-auto-colors.nvim";
      rev = "9be4af5b1bc1f26a11206ed7ce8bf44312e7941a";
      fetchSubmodules = false;
      sha256 = "sha256-JGI9y5Y0AocTO2M1Lt28UxVP0rZv20ZHJw0wKurJsh8=";
    };
    date = "2024-06-16";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "96fee098a90e7c09c9811aa7df71d773ba8b9b53";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "96fee098a90e7c09c9811aa7df71d773ba8b9b53";
      fetchSubmodules = false;
      sha256 = "sha256-D9kR4hD+sd+YnH7s66zbfMG2qKCxTeydU6ErpNzxhPU=";
    };
    date = "2024-07-15";
  };
  tree-sitter-nu = {
    pname = "tree-sitter-nu";
    version = "0bb9a602d9bc94b66fab96ce51d46a5a227ab76c";
    src = fetchgit {
      url = "https://github.com/nushell/tree-sitter-nu";
      rev = "0bb9a602d9bc94b66fab96ce51d46a5a227ab76c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-A5GiOpITOv3H0wytCv6t43buQ8IzxEXrk3gTlOrO0K0=";
    };
    date = "2024-06-13";
  };
  trouble = {
    pname = "trouble";
    version = "ad8ef38666834e9e438f84bd446657445bc2a71e";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "ad8ef38666834e9e438f84bd446657445bc2a71e";
      fetchSubmodules = false;
      sha256 = "sha256-9bwmXM0xW4IspLym7Er/snOztTvf+Wa3iTCFo5qBt80=";
    };
    date = "2024-07-19";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "f8c2e0b36b651c85f52ad5c5373ff8b07adc15a7";
      fetchSubmodules = false;
      sha256 = "sha256-8WH/eCff1liDVaezZFvu6RqCtXU4Uwq80BlWiH+tQME=";
    };
    date = "2024-07-18";
  };
  undotree = {
    pname = "undotree";
    version = "56c684a805fe948936cda0d1b19505b84ad7e065";
    src = fetchFromGitHub {
      owner = "mbbill";
      repo = "undotree";
      rev = "56c684a805fe948936cda0d1b19505b84ad7e065";
      fetchSubmodules = false;
      sha256 = "sha256-UIroW89ALMRdxSkNGU2VPeuXJxR+25wJ+AakRcjwx/s=";
    };
    date = "2024-04-16";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "0444df68cd1cdabc7453d6bd84099458327e5513";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "0444df68cd1cdabc7453d6bd84099458327e5513";
      fetchSubmodules = false;
      sha256 = "sha256-NLHaXpPrb4/QuVuTjl6YUUKA3/1r4VCOaNO48Dk9pms=";
    };
    date = "2024-07-18";
  };
}
