# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bufferline = {
    pname = "bufferline";
    version = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
    date = "2025-01-14";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "76a8d0515024cc55d8bd26fc13f1af88faef3ebf";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "76a8d0515024cc55d8bd26fc13f1af88faef3ebf";
      fetchSubmodules = false;
      sha256 = "sha256-3NVbHXmfaK/UmGz+EfLAT6iYV9F4CUGw/hB4RRccLGA=";
    };
    as = "catppuccin";
    date = "2025-08-04";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "0f2fd3829dd27d682e46c244cf48d9715726f612";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "0f2fd3829dd27d682e46c244cf48d9715726f612";
      fetchSubmodules = false;
      sha256 = "sha256-sfyitsBhociW5FN9tLAYAfuCKAWt/C+mKEmm/wUxoFo=";
    };
    date = "2025-08-01";
  };
  crates = {
    pname = "crates";
    version = "a49df0f70171adc77704eac70dd2c0d179065933";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "a49df0f70171adc77704eac70dd2c0d179065933";
      fetchSubmodules = false;
      sha256 = "sha256-b40E121rJrEmlor3fHmh4Y1TXKdfiqsBGBcpbY//eTw=";
    };
    date = "2025-08-06";
  };
  cuddlefish = {
    pname = "cuddlefish";
    version = "8381e244350e03b702422da97587d027ea1708fb";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "cuddlefish.nvim";
      rev = "8381e244350e03b702422da97587d027ea1708fb";
      fetchSubmodules = false;
      sha256 = "sha256-Nx++ZAL82tvSb8f0pHg+fIDm1D0q/PlQ/OOrOZTBsVM=";
    };
    date = "2025-08-04";
  };
  direnv = {
    pname = "direnv";
    version = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
      fetchSubmodules = false;
      sha256 = "sha256-KqO8uDbVy4sVVZ6mHikuO+SWCzWr97ZuFRC8npOPJIE=";
    };
    date = "2025-06-09";
  };
  evergarden = {
    pname = "evergarden";
    version = "4041ce92cf1387f19a8006c1e36969bfb5371c50";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "4041ce92cf1387f19a8006c1e36969bfb5371c50";
      fetchSubmodules = false;
      sha256 = "sha256-cPdpPSZCfJLJi0ZJEYV/HZlDK1Fjiktnqr3ELimrC+4=";
    };
    date = "2025-08-11";
  };
  fidget = {
    pname = "fidget";
    version = "2cb5edb2dd6700a958a446b20bb2be04d318da9d";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "2cb5edb2dd6700a958a446b20bb2be04d318da9d";
      fetchSubmodules = false;
      sha256 = "sha256-Hcnbk6go2vYCYqSfXLWQ+KimpU+NPbIkjBTKGMFoNQM=";
    };
    date = "2025-08-12";
  };
  formatter-nvim = {
    pname = "formatter-nvim";
    version = "b9d7f853da1197b83b8edb4cc4952f7ad3a42e41";
    src = fetchFromGitHub {
      owner = "mhartington";
      repo = "formatter.nvim";
      rev = "b9d7f853da1197b83b8edb4cc4952f7ad3a42e41";
      fetchSubmodules = false;
      sha256 = "sha256-SzM2P5RvnYUXYud2ubGtqdTXfQ3rshEusRWckH8a2E4=";
    };
    date = "2025-05-29";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "2f9e1af8cbff922543c2f259040d518517b8e294";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "2f9e1af8cbff922543c2f259040d518517b8e294";
      fetchSubmodules = false;
      sha256 = "sha256-oAJa194Muspw6l7LZUll9v/sq0uulgg2U8HbYs0sF84=";
    };
    date = "2025-08-12";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "6e3c66548035e50db7bd8e360a29aec6620c3641";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "6e3c66548035e50db7bd8e360a29aec6620c3641";
      fetchSubmodules = false;
      sha256 = "sha256-zBUrqL+00Y8j4eVNAgI0nYn2i35zhQo2BVl4mL1cgfs=";
    };
    date = "2025-08-12";
  };
  harpoon = {
    pname = "harpoon";
    version = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
      fetchSubmodules = false;
      sha256 = "sha256-L7FvOV6KvD58BnY3no5IudiKTdgkGqhpS85RoSxtl7U=";
    };
    date = "2025-02-10";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "d8b6b030672f9f551a0e3526347699985a779d93";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "d8b6b030672f9f551a0e3526347699985a779d93";
      fetchSubmodules = false;
      sha256 = "sha256-6hpSJbrJEnw5NaVkGrXxXeqkObNTUPCtKJd+iZBFUM0=";
    };
    date = "2025-06-08";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  lazydev = {
    pname = "lazydev";
    version = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
      fetchSubmodules = false;
      sha256 = "sha256-LoxziiV9jlHuU4vRVFfKtVLI45ouJcuyXC6DIyQKlew=";
    };
    date = "2025-02-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lualine = {
    pname = "lualine";
    version = "b8c23159c0161f4b89196f74ee3a6d02cdc3a955";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "b8c23159c0161f4b89196f74ee3a6d02cdc3a955";
      fetchSubmodules = false;
      sha256 = "sha256-lWt2kpW+hsTMWt8tar/+AISTDrIt4Jn27NmI9j+Xt4s=";
    };
    date = "2025-08-12";
  };
  lz-n = {
    pname = "lz-n";
    version = "da88560e12afc0fdca3dd901282fd2b95836fbb8";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "da88560e12afc0fdca3dd901282fd2b95836fbb8";
      fetchSubmodules = false;
      sha256 = "sha256-uMh7Q6PspGIRQtiIaiZYTWbilrB/8WMw17kW74e/syg=";
    };
    start = "true";
    date = "2025-08-03";
  };
  lzn-auto-require = {
    pname = "lzn-auto-require";
    version = "ef746afb55467984ef3200d9709c8059ee0257d0";
    src = fetchFromGitHub {
      owner = "horriblename";
      repo = "lzn-auto-require";
      rev = "ef746afb55467984ef3200d9709c8059ee0257d0";
      fetchSubmodules = false;
      sha256 = "sha256-KC1z+zC9vKODllZVpBu+udzM12oYJaS8e6LdXWtQ89U=";
    };
    start = "true";
    date = "2024-11-07";
  };
  markview = {
    pname = "markview";
    version = "2d68c060ad4387d9895577af43c3ace41a80de5d";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "2d68c060ad4387d9895577af43c3ace41a80de5d";
      fetchSubmodules = false;
      sha256 = "sha256-LKyHZ3mF2pivjAwXxjBVYNbSZ6a65D/u95HWH8vOe6A=";
    };
    date = "2025-08-04";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "b8f6fa6f5a3fd0c56936252edcd691184e5aac0c";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "b8f6fa6f5a3fd0c56936252edcd691184e5aac0c";
      fetchSubmodules = false;
      sha256 = "sha256-NTmY4He0rC+/wrPJ+9FoDoPFKT/TtmqG5IQhpmNd9B8=";
    };
    date = "2025-07-24";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "7a8606333affe7ce637a0ba91bbafc46fc42bfa0";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "7a8606333affe7ce637a0ba91bbafc46fc42bfa0";
      fetchSubmodules = false;
      sha256 = "sha256-rBr0oQScsEOkYy/iK3YMpwsa4ediCOFfdpsKPIEW2X4=";
    };
    date = "2025-08-12";
  };
  neo-tree = {
    pname = "neo-tree";
    version = "46fa0c22ca39e05fe15744102d21feb07fe9a94a";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "46fa0c22ca39e05fe15744102d21feb07fe9a94a";
      fetchSubmodules = false;
      sha256 = "sha256-RdrGoXN/R2ZrCsblEkOLpYsVd6SvBTzLxNg/hkmnx/E=";
    };
    date = "2025-07-29";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "3409dc920d40bec4c901c0a122a80bee03d6d1e1";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "3409dc920d40bec4c901c0a122a80bee03d6d1e1";
      fetchSubmodules = false;
      sha256 = "sha256-k2akj/s6qJx/sCnz3UNHo5zbENTpw+OPuo2WPF1W7rg=";
    };
    date = "2025-03-07";
  };
  nui = {
    pname = "nui";
    version = "de740991c12411b663994b2860f1a4fd0937c130";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "de740991c12411b663994b2860f1a4fd0937c130";
      fetchSubmodules = false;
      sha256 = "sha256-41slmnvt1z7sCxvpiVuFmQ9g7eCaxQi1dDCL3AxSL1A=";
    };
    date = "2025-06-08";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "16597180b4dd81fa3d23d88c4d2f1b49154f9479";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "16597180b4dd81fa3d23d88c4d2f1b49154f9479";
      fetchSubmodules = false;
      sha256 = "sha256-xj+FwjgeQ83VT/D8EeQn1ieA+fWS5910mRskTvI5mDo=";
    };
    date = "2025-07-22";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "7ef127aaede2a4d5ad8df8321e2eb4e567f29594";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "7ef127aaede2a4d5ad8df8321e2eb4e567f29594";
      fetchSubmodules = false;
      sha256 = "sha256-GmXScmbXJx74RMgPhkdKtdODZqkOarFHE1XOiSnt5Bo=";
    };
    date = "2025-07-31";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "45ff1914044de7dbd4cd85053dc09f47312a2f4d";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "45ff1914044de7dbd4cd85053dc09f47312a2f4d";
      fetchSubmodules = false;
      sha256 = "sha256-APKl0pvgqfVNVbHrcXCbJ4YMHANrK2LxGdoh5j3TJ3A=";
    };
    start = "true";
    date = "2025-08-12";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "f887d794a0f4594882814d7780980a949200a238";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "f887d794a0f4594882814d7780980a949200a238";
      fetchSubmodules = false;
      sha256 = "sha256-7L1rww1Z6NfcaOV5LUjspfwDhOk0asii8DdHmTe3ulc=";
    };
    date = "2025-05-09";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "bf0234010a49dc1df5de93390f197cfd0abcb9aa";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "bf0234010a49dc1df5de93390f197cfd0abcb9aa";
      fetchSubmodules = false;
      sha256 = "sha256-bPvMgB7BBz8tf+r8JUWcQMM49tl8kUckjrZDX5i+Wpc=";
    };
    start = "true";
    date = "2025-08-12";
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "4fd01de50c7fea3616f6809f19e9be8d2dc6ce63";
    src = fetchFromGitHub {
      owner = "obsidian-nvim";
      repo = "obsidian.nvim";
      rev = "4fd01de50c7fea3616f6809f19e9be8d2dc6ce63";
      fetchSubmodules = false;
      sha256 = "sha256-ZEyEwe/gSlO0uIabZ77GaT4b0hcwuzRRwr1+CXasDgs=";
    };
    date = "2025-08-13";
  };
  plenary = {
    pname = "plenary";
    version = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
      fetchSubmodules = false;
      sha256 = "sha256-9Un7ekhBxcnmFE1xjCCFTZ7eqIbmXvQexpnhduAg4M0=";
    };
    start = "true";
    date = "2025-07-26";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
      fetchSubmodules = false;
      sha256 = "sha256-Q5/2V+KvZSJ375/4lGC5x3CwcS0oSs1gB59PRTCXkn4=";
    };
    date = "2025-08-05";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
      fetchSubmodules = false;
      sha256 = "sha256-YzYhk9xksnZ6IMiKsE6ee6b3tUkZG6FAgLDErn9lvxA=";
    };
    date = "2025-07-24";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "eb606eb3785f6c6e31ef675c32b706694b76923b";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "eb606eb3785f6c6e31ef675c32b706694b76923b";
      fetchSubmodules = false;
      sha256 = "sha256-AlSjfgBwDndyNO3tHSOPMOqbH25nT65BZ7sf6f2IFgI=";
    };
    date = "2025-08-06";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "a28cc71857f11a7370d81f5ba3c1f5bb8383b732";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "a28cc71857f11a7370d81f5ba3c1f5bb8383b732";
      fetchSubmodules = false;
      sha256 = "sha256-0fdXvpFxDjCxeEUy/A9aVcksn30WrfBZMlMizW5UHvw=";
    };
    date = "2025-08-12";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "eab459ab87dd249617b5f7187bb69e614a083047";
    src = fetchFromGitHub {
      owner = "jiaoshijie";
      repo = "undotree";
      rev = "eab459ab87dd249617b5f7187bb69e614a083047";
      fetchSubmodules = false;
      sha256 = "sha256-FIYDyfkaIS9C16ClWKLMdpSPv/OrcOalVVsyFJBU2eI=";
    };
    date = "2024-02-09";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
      fetchSubmodules = false;
      sha256 = "sha256-u39oObHCXk8uew5HyVdV1Z69Viilv3B7x1SUJxYXYLo=";
    };
    date = "2025-07-15";
  };
  wakatime = {
    pname = "wakatime";
    version = "3403495670f0ee08887401a28f8430dc4ac67429";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "3403495670f0ee08887401a28f8430dc4ac67429";
      fetchSubmodules = false;
      sha256 = "sha256-vUw0MCQ6TD9j7e61o+9hluUMLORgWjqTQJH25geNxiU=";
    };
    date = "2025-07-26";
  };
}
