# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bufferline = {
    pname = "bufferline";
    version = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
    date = "2025-01-14";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "30fa4d122d9b22ad8b2e0ab1b533c8c26c4dde86";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "30fa4d122d9b22ad8b2e0ab1b533c8c26c4dde86";
      fetchSubmodules = false;
      sha256 = "sha256-o8VLMPriOh4+Ay5Ff0cWQYXjmihdr3x9131bKHHTsQE=";
    };
    as = "catppuccin";
    date = "2025-08-19";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "e73fe7c43c68aeb84fbeed12ee6cc60a29e78fbb";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "e73fe7c43c68aeb84fbeed12ee6cc60a29e78fbb";
      fetchSubmodules = false;
      sha256 = "sha256-C1ayQc4kGdXabGnqBYwzqDqJw5RISGXMHyb3wUXDrv8=";
    };
    date = "2025-08-29";
  };
  crates = {
    pname = "crates";
    version = "ac9fa498a9edb96dc3056724ff69d5f40b898453";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "ac9fa498a9edb96dc3056724ff69d5f40b898453";
      fetchSubmodules = false;
      sha256 = "sha256-jfmST/S9ymwgQ99PTCOlJkk5zaxE5HiDV16TmTISDII=";
    };
    date = "2025-08-23";
  };
  cuddlefish = {
    pname = "cuddlefish";
    version = "8381e244350e03b702422da97587d027ea1708fb";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "cuddlefish.nvim";
      rev = "8381e244350e03b702422da97587d027ea1708fb";
      fetchSubmodules = false;
      sha256 = "sha256-Nx++ZAL82tvSb8f0pHg+fIDm1D0q/PlQ/OOrOZTBsVM=";
    };
    date = "2025-08-04";
  };
  direnv = {
    pname = "direnv";
    version = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "4dfc8758a1deab45e37b7f3661e0fd3759d85788";
      fetchSubmodules = false;
      sha256 = "sha256-KqO8uDbVy4sVVZ6mHikuO+SWCzWr97ZuFRC8npOPJIE=";
    };
    date = "2025-06-09";
  };
  evergarden = {
    pname = "evergarden";
    version = "4041ce92cf1387f19a8006c1e36969bfb5371c50";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "4041ce92cf1387f19a8006c1e36969bfb5371c50";
      fetchSubmodules = false;
      sha256 = "sha256-cPdpPSZCfJLJi0ZJEYV/HZlDK1Fjiktnqr3ELimrC+4=";
    };
    date = "2025-08-11";
  };
  fidget = {
    pname = "fidget";
    version = "4d5858bd4c471c895060e1b9f3575f1551184dc5";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "4d5858bd4c471c895060e1b9f3575f1551184dc5";
      fetchSubmodules = false;
      sha256 = "sha256-KRlUqUdcliKpLnEJqyA2OAWto73F6iGTbMrsiAdc24M=";
    };
    date = "2025-08-20";
  };
  formatter-nvim = {
    pname = "formatter-nvim";
    version = "b9d7f853da1197b83b8edb4cc4952f7ad3a42e41";
    src = fetchFromGitHub {
      owner = "mhartington";
      repo = "formatter.nvim";
      rev = "b9d7f853da1197b83b8edb4cc4952f7ad3a42e41";
      fetchSubmodules = false;
      sha256 = "sha256-SzM2P5RvnYUXYud2ubGtqdTXfQ3rshEusRWckH8a2E4=";
    };
    date = "2025-05-29";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  fzf-lua = {
    pname = "fzf-lua";
    version = "2dce48dac09cec8143820f1d33381fe6d03a3900";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "fzf-lua";
      rev = "2dce48dac09cec8143820f1d33381fe6d03a3900";
      fetchSubmodules = false;
      sha256 = "sha256-bX+99rp+x0MKxjCnvypni+DNSEVsDmfpRO3WaWqlBdE=";
    };
    date = "2025-09-02";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "6e3c66548035e50db7bd8e360a29aec6620c3641";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "6e3c66548035e50db7bd8e360a29aec6620c3641";
      fetchSubmodules = false;
      sha256 = "sha256-zBUrqL+00Y8j4eVNAgI0nYn2i35zhQo2BVl4mL1cgfs=";
    };
    date = "2025-08-12";
  };
  harpoon = {
    pname = "harpoon";
    version = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
      fetchSubmodules = false;
      sha256 = "sha256-L7FvOV6KvD58BnY3no5IudiKTdgkGqhpS85RoSxtl7U=";
    };
    date = "2025-02-10";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "f33f3af9ba50f99d70f8fcb1a8575750ada4ea4a";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "f33f3af9ba50f99d70f8fcb1a8575750ada4ea4a";
      fetchSubmodules = false;
      sha256 = "sha256-o781gHd3sJEEgAMXX+/YXi80pnn0XF35LVwJjLqc0RQ=";
    };
    date = "2025-08-30";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  lazydev = {
    pname = "lazydev";
    version = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
      fetchSubmodules = false;
      sha256 = "sha256-LoxziiV9jlHuU4vRVFfKtVLI45ouJcuyXC6DIyQKlew=";
    };
    date = "2025-02-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lualine = {
    pname = "lualine";
    version = "b8c23159c0161f4b89196f74ee3a6d02cdc3a955";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "b8c23159c0161f4b89196f74ee3a6d02cdc3a955";
      fetchSubmodules = false;
      sha256 = "sha256-lWt2kpW+hsTMWt8tar/+AISTDrIt4Jn27NmI9j+Xt4s=";
    };
    date = "2025-08-12";
  };
  lz-n = {
    pname = "lz-n";
    version = "07b7f18a998733d66214da8fe322443f32476d44";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "07b7f18a998733d66214da8fe322443f32476d44";
      fetchSubmodules = false;
      sha256 = "sha256-iFpo/9UD3iygIbpIhsnsF9y3P7+Xy8je2Ne1NA+XRu8=";
    };
    start = "true";
    date = "2025-09-02";
  };
  lzn-auto-require = {
    pname = "lzn-auto-require";
    version = "ef746afb55467984ef3200d9709c8059ee0257d0";
    src = fetchFromGitHub {
      owner = "horriblename";
      repo = "lzn-auto-require";
      rev = "ef746afb55467984ef3200d9709c8059ee0257d0";
      fetchSubmodules = false;
      sha256 = "sha256-KC1z+zC9vKODllZVpBu+udzM12oYJaS8e6LdXWtQ89U=";
    };
    start = "true";
    date = "2024-11-07";
  };
  markview = {
    pname = "markview";
    version = "e6b0f5aee8105adab6077509c46459812db4cffa";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "e6b0f5aee8105adab6077509c46459812db4cffa";
      fetchSubmodules = false;
      sha256 = "sha256-J/wo3OO+iOjyaPpBlRvrJu/VDma53ufeiegivJBpDM0=";
    };
    date = "2025-09-01";
  };
  mini-icons = {
    pname = "mini-icons";
    version = "f9a177c11daa7829389b7b6eaaec8b8a5c47052d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.icons";
      rev = "f9a177c11daa7829389b7b6eaaec8b8a5c47052d";
      fetchSubmodules = false;
      sha256 = "sha256-Br5LHQtHJ21NWBwb9TofQhQ8HaUlF7lkKBx7fpjcHwk=";
    };
    date = "2025-08-28";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "953fb53aa1d0b2ae4506d35fff0e0e7afc8ceb8d";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "953fb53aa1d0b2ae4506d35fff0e0e7afc8ceb8d";
      fetchSubmodules = false;
      sha256 = "sha256-WjasSMDQqRVFrf/9flDL25xglsYNDBKi9/dVEHlhiDw=";
    };
    date = "2025-08-28";
  };
  neo-tree = {
    pname = "neo-tree";
    version = "ed057048a281b418d5318dd5153f9486daa517a3";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "ed057048a281b418d5318dd5153f9486daa517a3";
      fetchSubmodules = false;
      sha256 = "sha256-SacuWtkoaTW8ubxbfrylTjZ4a0KGEgyxWHk7iswzBpI=";
    };
    date = "2025-09-01";
  };
  nivvie-nvim = {
    pname = "nivvie-nvim";
    version = "f2ee7cd6aae80f7b3a7ed9c6f7c3b21110fb5706";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "nivvie.nvim";
      rev = "f2ee7cd6aae80f7b3a7ed9c6f7c3b21110fb5706";
      fetchSubmodules = false;
      sha256 = "sha256-sUHC146fALmpBcyk6yW8uIdBXVzu5oBHuTr/sGMq3sc=";
    };
    date = "2025-08-21";
  };
  nui = {
    pname = "nui";
    version = "de740991c12411b663994b2860f1a4fd0937c130";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "de740991c12411b663994b2860f1a4fd0937c130";
      fetchSubmodules = false;
      sha256 = "sha256-41slmnvt1z7sCxvpiVuFmQ9g7eCaxQi1dDCL3AxSL1A=";
    };
    date = "2025-06-08";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "51cf7c995ed1eb6642aecf19067ee634fa1b6ba2";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "51cf7c995ed1eb6642aecf19067ee634fa1b6ba2";
      fetchSubmodules = false;
      sha256 = "sha256-VlVeRTtzfeS3OlN7d9P5cmqN9Go0XMpTp36RSGq7sr8=";
    };
    date = "2025-08-13";
  };
  nvim-lint = {
    pname = "nvim-lint";
    version = "f126af5345c7472e9a0cdbe1d1a29209be72c4c4";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "f126af5345c7472e9a0cdbe1d1a29209be72c4c4";
      fetchSubmodules = false;
      sha256 = "sha256-hNMvXw+IwWtLnrmu6waKgMGcaWX46EkHNgBYvLZ+XeE=";
    };
    date = "2025-08-28";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "060f6b601b8d60d59fb2f6dfb2528c391bcd60a2";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "060f6b601b8d60d59fb2f6dfb2528c391bcd60a2";
      fetchSubmodules = false;
      sha256 = "sha256-6usg3Gb0hvhFLph5M645EPMmHsq1zZ8b95WbZ3ydWJU=";
    };
    start = "true";
    date = "2025-09-02";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "f887d794a0f4594882814d7780980a949200a238";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "f887d794a0f4594882814d7780980a949200a238";
      fetchSubmodules = false;
      sha256 = "sha256-7L1rww1Z6NfcaOV5LUjspfwDhOk0asii8DdHmTe3ulc=";
    };
    date = "2025-05-09";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "802195d8f1980db25a7a39a55f9a25df21756c73";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "802195d8f1980db25a7a39a55f9a25df21756c73";
      fetchSubmodules = false;
      sha256 = "sha256-UR9cj1pYXSZ5gYvY1tj+/8ZLsK2uzY2owxCOeqb08f4=";
    };
    start = "true";
    date = "2025-08-31";
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "252e5430cd3ee234f6a600030511fb3e6a6ebbb0";
    src = fetchFromGitHub {
      owner = "obsidian-nvim";
      repo = "obsidian.nvim";
      rev = "252e5430cd3ee234f6a600030511fb3e6a6ebbb0";
      fetchSubmodules = false;
      sha256 = "sha256-lBVI2irRLX5+rxYqKWDL4t/6f1Wg2FfPLNN7m+MiXgc=";
    };
    date = "2025-09-02";
  };
  plenary = {
    pname = "plenary";
    version = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
      fetchSubmodules = false;
      sha256 = "sha256-9Un7ekhBxcnmFE1xjCCFTZ7eqIbmXvQexpnhduAg4M0=";
    };
    start = "true";
    date = "2025-07-26";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "c3e40509b6f4a428091fb1e42c3e992ba0e09fb0";
      fetchSubmodules = false;
      sha256 = "sha256-Q5/2V+KvZSJ375/4lGC5x3CwcS0oSs1gB59PRTCXkn4=";
    };
    date = "2025-08-05";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "97bf4b8ef9298644a29fcd9dd41a0210cf08cac7";
      fetchSubmodules = false;
      sha256 = "sha256-YzYhk9xksnZ6IMiKsE6ee6b3tUkZG6FAgLDErn9lvxA=";
    };
    date = "2025-07-24";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "12504405821c05874d2d1f6b5ec919f9808e2c99";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "12504405821c05874d2d1f6b5ec919f9808e2c99";
      fetchSubmodules = false;
      sha256 = "sha256-QpkRrjF1Am+YFgv+T8p8jhM45LGZD5UNejV5oEY4b64=";
    };
    date = "2025-08-31";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "dc34600801650c2c8bf62125b1f70f6cfffcc057";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "dc34600801650c2c8bf62125b1f70f6cfffcc057";
      fetchSubmodules = false;
      sha256 = "sha256-uhKC7zXYCvRe5AV+U1cHbxzMUnxCgmqJscGX8VGkE7I=";
    };
    date = "2025-08-31";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  undotree = {
    pname = "undotree";
    version = "444a7b0a96648eaed2aae7e0d07f5096896a188c";
    src = fetchFromGitHub {
      owner = "jiaoshijie";
      repo = "undotree";
      rev = "444a7b0a96648eaed2aae7e0d07f5096896a188c";
      fetchSubmodules = false;
      sha256 = "sha256-49vTcbJ14G9cX+5C3mQtVIcHuy4UIF5BWS8/mlk1RGE=";
    };
    date = "2025-09-02";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "61b51c09b7c9ce04e821f6cf76ea4f6f903e3cf4";
      fetchSubmodules = false;
      sha256 = "sha256-u39oObHCXk8uew5HyVdV1Z69Viilv3B7x1SUJxYXYLo=";
    };
    date = "2025-07-15";
  };
  wakatime = {
    pname = "wakatime";
    version = "d7973b157a632d1edeff01818f18d67e584eeaff";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "d7973b157a632d1edeff01818f18d67e584eeaff";
      fetchSubmodules = false;
      sha256 = "sha256-yr63v1aU7Rh9ndj5oAOfwKZnPCN/syeBjUdEY6QUcPc=";
    };
    date = "2025-08-30";
  };
}
