# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha = {
    pname = "alpha";
    version = "de72250e054e5e691b9736ee30db72c65d560771";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "de72250e054e5e691b9736ee30db72c65d560771";
      fetchSubmodules = false;
      sha256 = "sha256-sNi5qarejYqM4/J7lBZI3gjVLxer5FBPq8K6qjqcMjA=";
    };
    date = "2024-11-14";
  };
  bufferline = {
    pname = "bufferline";
    version = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
    date = "2025-01-14";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "8162a4bd9afb42837a655e404d1f937a87ba95e6";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "8162a4bd9afb42837a655e404d1f937a87ba95e6";
      fetchSubmodules = false;
      sha256 = "sha256-u3E/vyii4zD491GEffbscMU3teDOgt3bFWaYwnaX7E0=";
    };
    as = "catppuccin";
    date = "2025-05-17";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "96e1bb1963f351700bf6737ef3695e8a0b90b12a";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "96e1bb1963f351700bf6737ef3695e8a0b90b12a";
      fetchSubmodules = false;
      sha256 = "sha256-W468TRmW77Yh+RrEsFZbm+CILVOFU8+CmyFgerI4JX4=";
    };
    date = "2025-05-20";
  };
  crates = {
    pname = "crates";
    version = "25f31372ab6f504d4fd7cfee836ad459caed8e68";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "25f31372ab6f504d4fd7cfee836ad459caed8e68";
      fetchSubmodules = false;
      sha256 = "sha256-UEDDXObbUX25AJQXl9itjJ1N2AlYYExvzPenX6rdr28=";
    };
    date = "2025-05-14";
  };
  cuddlefish = {
    pname = "cuddlefish";
    version = "6448a5f44628dbf8677d72bd3e9ad6e89bd6a7d8";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "cuddlefish.nvim";
      rev = "6448a5f44628dbf8677d72bd3e9ad6e89bd6a7d8";
      fetchSubmodules = false;
      sha256 = "sha256-ZZ5kE/MikATxbtmhoXYvkxRaIgseCDAkfZse4NaWoes=";
    };
    date = "2025-04-17";
  };
  direnv = {
    pname = "direnv";
    version = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
      fetchSubmodules = false;
      sha256 = "sha256-nAnZte8okf8V6gH2Egy/32o3W8xznbYhsYBPQ+9F470=";
    };
    date = "2025-04-23";
  };
  evergarden = {
    pname = "evergarden";
    version = "d4612a121151ccc98a45802a93ce8321700a2a52";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "d4612a121151ccc98a45802a93ce8321700a2a52";
      fetchSubmodules = false;
      sha256 = "sha256-0+I2Y0bE1IYiHQo1ELkLcxWPmWg5g3d2KIlqNnFbaZI=";
    };
    date = "2025-05-18";
  };
  fidget = {
    pname = "fidget";
    version = "d9ba6b7bfe29b3119a610892af67602641da778e";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "d9ba6b7bfe29b3119a610892af67602641da778e";
      fetchSubmodules = false;
      sha256 = "sha256-AFUx/ZQVWV7s5Wlppjk6N9QXoJKNKqxtf990FFlTEhw=";
    };
    date = "2025-02-05";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "ee0606259ee5d5dd40398be26755048e8965086e";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "ee0606259ee5d5dd40398be26755048e8965086e";
      fetchSubmodules = false;
      sha256 = "sha256-kpTQxfXxRfiNSrgKip63kMzPivqFkqx5A0sZsQTFRBY=";
    };
    date = "2025-05-19";
  };
  harpoon = {
    pname = "harpoon";
    version = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
      fetchSubmodules = false;
      sha256 = "sha256-L7FvOV6KvD58BnY3no5IudiKTdgkGqhpS85RoSxtl7U=";
    };
    date = "2025-02-10";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
      fetchSubmodules = false;
      sha256 = "sha256-6STviireN52R7engW3c0R2Po8hHSP/apqhXvectH0So=";
    };
    date = "2025-04-01";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  lazydev = {
    pname = "lazydev";
    version = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
      fetchSubmodules = false;
      sha256 = "sha256-LoxziiV9jlHuU4vRVFfKtVLI45ouJcuyXC6DIyQKlew=";
    };
    date = "2025-02-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
      fetchSubmodules = false;
      sha256 = "sha256-OCvKUBGuzwy8OWOL1x3Z3fo+0+GyBMI9TX41xSveqvE=";
    };
    date = "2024-12-05";
  };
  lualine = {
    pname = "lualine";
    version = "0c6cca9f2c63dadeb9225c45bc92bb95a151d4af";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "0c6cca9f2c63dadeb9225c45bc92bb95a151d4af";
      fetchSubmodules = false;
      sha256 = "sha256-Z6efNmO6nvaNASYS9d0WcazJm7OJyp/kbgREEI/JHIc=";
    };
    date = "2025-05-21";
  };
  luasnip = {
    pname = "luasnip";
    version = "c1851d5c519611dfc451b6582961b2602e0af89b";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "c1851d5c519611dfc451b6582961b2602e0af89b";
      fetchSubmodules = false;
      sha256 = "sha256-0w4ZQe/K4SDK5N745c+E/DqeT2e4dMxMf8MjX8fUOO0=";
    };
    as = "luasnip";
    date = "2025-05-12";
  };
  lz-n = {
    pname = "lz-n";
    version = "73db788f11ef798b848f82d147a7c8fb8cea25f3";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "73db788f11ef798b848f82d147a7c8fb8cea25f3";
      fetchSubmodules = false;
      sha256 = "sha256-MQ5dDK3Its/dNxaQWJM0yBqT0m4t9gkmrZT7hJ1cMTw=";
    };
    start = "true";
    date = "2025-05-18";
  };
  markview = {
    pname = "markview";
    version = "caa689a1defabe56752f5d1dcea35a2c4eb97c0f";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "caa689a1defabe56752f5d1dcea35a2c4eb97c0f";
      fetchSubmodules = false;
      sha256 = "sha256-nrNg0SsykLH3smp6biEv4BZpRjPeovr9BQfju/+xNIA=";
    };
    date = "2025-05-21";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "5aab42fcdcf31fa010f012771eda5631c077840a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "5aab42fcdcf31fa010f012771eda5631c077840a";
      fetchSubmodules = false;
      sha256 = "sha256-fsJf1wOLPLSjAgGcjrckwrK1qkpyPjKHMeqEj589XkM=";
    };
    date = "2025-04-01";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "3409dc920d40bec4c901c0a122a80bee03d6d1e1";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "3409dc920d40bec4c901c0a122a80bee03d6d1e1";
      fetchSubmodules = false;
      sha256 = "sha256-k2akj/s6qJx/sCnz3UNHo5zbENTpw+OPuo2WPF1W7rg=";
    };
    date = "2025-03-07";
  };
  none-ls = {
    pname = "none-ls";
    version = "90e4a27ccaa25979a6b732b9f06dfa43b54957b7";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "90e4a27ccaa25979a6b732b9f06dfa43b54957b7";
      fetchSubmodules = false;
      sha256 = "sha256-nLv9XR6uBFCK9peAjcq7yWLr7bfefrCzlSAp3SbdE9s=";
    };
    date = "2025-05-12";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "517df88cf2afb36652830df2c655df2da416a0ae";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "517df88cf2afb36652830df2c655df2da416a0ae";
      fetchSubmodules = false;
      sha256 = "sha256-yOPUgqHe0WT437aX8kp0P/reNgjZUNNRG7hvDgaeXT0=";
    };
    date = "2025-03-01";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "ac1dfbe3b60e5e23a2cff90e3bd6a3bc88031a57";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "ac1dfbe3b60e5e23a2cff90e3bd6a3bc88031a57";
      fetchSubmodules = false;
      sha256 = "sha256-iC1l9KefzVbRKsqEqvxUdokBvWxIQahr8KJ+K1j16Sw=";
    };
    date = "2025-05-14";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "f887d794a0f4594882814d7780980a949200a238";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "f887d794a0f4594882814d7780980a949200a238";
      fetchSubmodules = false;
      sha256 = "sha256-7L1rww1Z6NfcaOV5LUjspfwDhOk0asii8DdHmTe3ulc=";
    };
    date = "2025-05-09";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "b5825cf9ee881dd8e43309c93374ed5b87b7a896";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "b5825cf9ee881dd8e43309c93374ed5b87b7a896";
      fetchSubmodules = false;
      sha256 = "sha256-m4dQ8KuMhbEpRh6zLTlIUDN9ojFj69LZnXXLepmdFI8=";
    };
    date = "2025-04-13";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "25d16aab7d29ca940a9feb92e6bb734697417009";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "25d16aab7d29ca940a9feb92e6bb734697417009";
      fetchSubmodules = false;
      sha256 = "sha256-mxN3pOW2KCodSq8bPhtUqTgrZFjwIS60Wg3yornkunQ=";
    };
    date = "2025-05-18";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "1fb58cca9aebbc4fd32b086cb413548ce132c127";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "1fb58cca9aebbc4fd32b086cb413548ce132c127";
      fetchSubmodules = false;
      sha256 = "sha256-+RHeFaeCF/iwAf8qAOjbEIl3YcnrBMVfkQnnzDNhyTA=";
    };
    date = "2025-05-16";
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "9ada1217e6d03dee9b51ea73d120b8986ef1e612";
    src = fetchFromGitHub {
      owner = "obsidian-nvim";
      repo = "obsidian.nvim";
      rev = "9ada1217e6d03dee9b51ea73d120b8986ef1e612";
      fetchSubmodules = false;
      sha256 = "sha256-u5BgBdvui/4tgOE+c4eeSJr7fm4Vrp6Y79Iu3oM5e6Q=";
    };
    date = "2025-05-19";
  };
  plenary = {
    pname = "plenary";
    version = "857c5ac632080dba10aae49dba902ce3abf91b35";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "857c5ac632080dba10aae49dba902ce3abf91b35";
      fetchSubmodules = false;
      sha256 = "sha256-8FV5RjF7QbDmQOQynpK7uRKONKbPRYbOPugf9ZxNvUs=";
    };
    start = "true";
    date = "2025-02-11";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "63169f3c63896e1286ffdfe06642cab55eaa6b3c";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "63169f3c63896e1286ffdfe06642cab55eaa6b3c";
      fetchSubmodules = false;
      sha256 = "sha256-80zbogGoR1prFo0rHZEme3ILsBOJM9YcJkerylxDGEk=";
    };
    date = "2025-03-11";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "55ad4fb76ab68460f700599b7449385f0c4e858e";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "55ad4fb76ab68460f700599b7449385f0c4e858e";
      fetchSubmodules = false;
      sha256 = "sha256-EeJvGtBwZgR7i9PEnGe4NTRiDQCgVKkSh5t8Xy5EYfE=";
    };
    date = "2025-04-16";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "1e1106492f7e4512642603db34e542c938ad579c";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "1e1106492f7e4512642603db34e542c938ad579c";
      fetchSubmodules = false;
      sha256 = "sha256-H1xjUSalglgHFlu2dxCtSQArh80pXbgW5PGdq2kJTCA=";
    };
    date = "2025-05-20";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "386bdbf18abb6ca103495c5bdbab65e46f3c361d";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "386bdbf18abb6ca103495c5bdbab65e46f3c361d";
      fetchSubmodules = false;
      sha256 = "sha256-ysxgGpMgeLOWKGKotdvUkTVODpW5ioIRk72W7trfVs0=";
    };
    date = "2025-05-17";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  telescope = {
    pname = "telescope";
    version = "b4da76be54691e854d3e0e02c36b0245f945c2c7";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "b4da76be54691e854d3e0e02c36b0245f945c2c7";
      fetchSubmodules = false;
      sha256 = "sha256-JpW0ehsX81yVbKNzrYOe1hdgVMs6oaaxMLH6lECnOJg=";
    };
    date = "2025-05-11";
  };
  telescope-project = {
    pname = "telescope-project";
    version = "8e11df94419e444601c09828dadf70890484e443";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "8e11df94419e444601c09828dadf70890484e443";
      fetchSubmodules = false;
      sha256 = "sha256-RyrfT/uQmuer+WN9Q58InTkuFJO+VQvVsp0ZRpRp7PQ=";
    };
    date = "2025-04-23";
  };
  telescope-ui-select = {
    pname = "telescope-ui-select";
    version = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
      fetchSubmodules = false;
      sha256 = "sha256-YRhNmmG4gx9Ht8JwjQfbTjJyTHEuZmtP6lqnhOsk8bE=";
    };
    date = "2023-12-04";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "3c501d7c7f79457932a8750a2a1476a004c5c1a9";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "3c501d7c7f79457932a8750a2a1476a004c5c1a9";
      fetchSubmodules = false;
      sha256 = "sha256-roSEM3YGfKIoGQIlvaC0IFCIzkPLhJmnUMc+CBQmQE8=";
    };
    date = "2025-04-25";
  };
  undotree = {
    pname = "undotree";
    version = "eab459ab87dd249617b5f7187bb69e614a083047";
    src = fetchFromGitHub {
      owner = "jiaoshijie";
      repo = "undotree";
      rev = "eab459ab87dd249617b5f7187bb69e614a083047";
      fetchSubmodules = false;
      sha256 = "sha256-FIYDyfkaIS9C16ClWKLMdpSPv/OrcOalVVsyFJBU2eI=";
    };
    date = "2024-02-09";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
      fetchSubmodules = false;
      sha256 = "sha256-1AteNwnc7lCHLIwM8Ejm2T9VTIDM+CeAfvAUeSQRFKE=";
    };
    date = "2025-02-19";
  };
  wakatime = {
    pname = "wakatime";
    version = "cb037fb53e718c4f0027a491782ad99efdcd789a";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "cb037fb53e718c4f0027a491782ad99efdcd789a";
      fetchSubmodules = false;
      sha256 = "sha256-l0neRkEKePw0MNvFr6ecBogVIMNnSQMmIMYKK6lQk60=";
    };
    date = "2025-05-16";
  };
}
