# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha = {
    pname = "alpha";
    version = "de72250e054e5e691b9736ee30db72c65d560771";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "de72250e054e5e691b9736ee30db72c65d560771";
      fetchSubmodules = false;
      sha256 = "sha256-sNi5qarejYqM4/J7lBZI3gjVLxer5FBPq8K6qjqcMjA=";
    };
    date = "2024-11-14";
  };
  bufferline = {
    pname = "bufferline";
    version = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "655133c3b4c3e5e05ec549b9f8cc2894ac6f51b3";
      fetchSubmodules = false;
      sha256 = "sha256-ae4MB6+6v3awvfSUWlau9ASJ147ZpwuX1fvJdfMwo1Q=";
    };
    date = "2025-01-14";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "5b5e3aef9ad7af84f463d17b5479f06b87d5c429";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "5b5e3aef9ad7af84f463d17b5479f06b87d5c429";
      fetchSubmodules = false;
      sha256 = "sha256-4h/fzFY8JR9r+QnoiWEqgQKPMuu8i9HTC4v0Jp7iuUo=";
    };
    as = "catppuccin";
    date = "2025-03-01";
  };
  cloak = {
    pname = "cloak";
    version = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
    src = fetchFromGitHub {
      owner = "laytan";
      repo = "cloak.nvim";
      rev = "648aca6d33ec011dc3166e7af3b38820d01a71e4";
      fetchSubmodules = false;
      sha256 = "sha256-V7oNIu7IBAHqSrgCNoePNUPjQDU9cFThFf7XGIth0sk=";
    };
    date = "2024-06-12";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "a5c390f8d8e85b501b22dcb2f30e0cbbd69d5ff0";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "a5c390f8d8e85b501b22dcb2f30e0cbbd69d5ff0";
      fetchSubmodules = false;
      sha256 = "sha256-8zXdRLugrLRK+sg9k9I1MSE5KAdnY017IkquCQisZt4=";
    };
    date = "2025-04-25";
  };
  crates = {
    pname = "crates";
    version = "2c8f4fab02e3e9ea42c6ad9b547e4207a914a397";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "2c8f4fab02e3e9ea42c6ad9b547e4207a914a397";
      fetchSubmodules = false;
      sha256 = "sha256-Oh3krtXo38wwrcc9YWLS0uw3q7tuw8eU/QG+sUmqtDU=";
    };
    date = "2025-04-29";
  };
  cuddlefish = {
    pname = "cuddlefish";
    version = "6448a5f44628dbf8677d72bd3e9ad6e89bd6a7d8";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "cuddlefish.nvim";
      rev = "6448a5f44628dbf8677d72bd3e9ad6e89bd6a7d8";
      fetchSubmodules = false;
      sha256 = "sha256-ZZ5kE/MikATxbtmhoXYvkxRaIgseCDAkfZse4NaWoes=";
    };
    date = "2025-04-17";
  };
  direnv = {
    pname = "direnv";
    version = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
    src = fetchFromGitHub {
      owner = "NotAShelf";
      repo = "direnv.nvim";
      rev = "a2f1264909463fd012b7b0b6bbfebc282c5d2834";
      fetchSubmodules = false;
      sha256 = "sha256-nAnZte8okf8V6gH2Egy/32o3W8xznbYhsYBPQ+9F470=";
    };
    date = "2025-04-23";
  };
  evergarden = {
    pname = "evergarden";
    version = "de538e9aac1358872c118e0d7bc45462fc8205c8";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "evergarden";
      rev = "de538e9aac1358872c118e0d7bc45462fc8205c8";
      fetchSubmodules = false;
      sha256 = "sha256-CiRiZRmD7tuy/fNQwYJohiS1KSL+7ihTm29cMHunUWE=";
    };
    date = "2025-04-25";
  };
  fidget = {
    pname = "fidget";
    version = "d9ba6b7bfe29b3119a610892af67602641da778e";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "d9ba6b7bfe29b3119a610892af67602641da778e";
      fetchSubmodules = false;
      sha256 = "sha256-AFUx/ZQVWV7s5Wlppjk6N9QXoJKNKqxtf990FFlTEhw=";
    };
    date = "2025-02-05";
  };
  freeze = {
    pname = "freeze";
    version = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
    src = fetchFromGitHub {
      owner = "charm-community";
      repo = "freeze.nvim";
      rev = "590fdb0d724485f578e4fee0e3ae2b32040dfb1a";
      fetchSubmodules = false;
      sha256 = "sha256-VdFmSRBP7Up0j5+rp7ZkfTdQmduJjsl6EZ9gf27vgZg=";
    };
    date = "2025-03-25";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "ee28ba3e70ecea811b8f6d7b51d81976e94b121c";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "ee28ba3e70ecea811b8f6d7b51d81976e94b121c";
      fetchSubmodules = false;
      sha256 = "sha256-tp/ieCpa0Y0crEHW7NwXO+z18H1OIqXWPy2wn20KFZU=";
    };
    date = "2025-04-30";
  };
  harpoon = {
    pname = "harpoon";
    version = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "ed1f853847ffd04b2b61c314865665e1dadf22c7";
      fetchSubmodules = false;
      sha256 = "sha256-L7FvOV6KvD58BnY3no5IudiKTdgkGqhpS85RoSxtl7U=";
    };
    date = "2025-02-10";
  };
  img-clip-nvim = {
    pname = "img-clip-nvim";
    version = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
    src = fetchFromGitHub {
      owner = "HakonHarnes";
      repo = "img-clip.nvim";
      rev = "08a02e14c8c0d42fa7a92c30a98fd04d6993b35d";
      fetchSubmodules = false;
      sha256 = "sha256-6STviireN52R7engW3c0R2Po8hHSP/apqhXvectH0So=";
    };
    date = "2025-04-01";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "005b56001b2cb30bfa61b7986bc50657816ba4ba";
      fetchSubmodules = false;
      sha256 = "sha256-0q/V+b4UrDRnaC/eRWOi9HU9a61vQSAM9/C8ZQyKt+Y=";
    };
    date = "2025-03-18";
  };
  lazydev = {
    pname = "lazydev";
    version = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "2367a6c0a01eb9edb0464731cc0fb61ed9ab9d2c";
      fetchSubmodules = false;
      sha256 = "sha256-LoxziiV9jlHuU4vRVFfKtVLI45ouJcuyXC6DIyQKlew=";
    };
    date = "2025-02-20";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "d79a1c3299ad0ef94e255d045bed9fa26025dab6";
      fetchSubmodules = false;
      sha256 = "sha256-OCvKUBGuzwy8OWOL1x3Z3fo+0+GyBMI9TX41xSveqvE=";
    };
    date = "2024-12-05";
  };
  lualine = {
    pname = "lualine";
    version = "15884cee63a8c205334ab13ab1c891cd4d27101a";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "15884cee63a8c205334ab13ab1c891cd4d27101a";
      fetchSubmodules = false;
      sha256 = "sha256-wfNEDR3uR8Y6hZhzcnuukQ2yMz7rCvuc4li/0rkPRTA=";
    };
    date = "2025-04-22";
  };
  luasnip = {
    pname = "luasnip";
    version = "c9b9a22904c97d0eb69ccb9bab76037838326817";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "c9b9a22904c97d0eb69ccb9bab76037838326817";
      fetchSubmodules = false;
      sha256 = "sha256-3ecm5SDTcSOh256xSQPHhddQfMpepiEIpv58fHXrVg0=";
    };
    as = "luasnip";
    date = "2025-01-04";
  };
  lz-n = {
    pname = "lz-n";
    version = "a10519ab5940a5364560043df9dc3db328e27f98";
    src = fetchFromGitHub {
      owner = "nvim-neorocks";
      repo = "lz.n";
      rev = "a10519ab5940a5364560043df9dc3db328e27f98";
      fetchSubmodules = false;
      sha256 = "sha256-YYYO8ZrK45b2NTb7CFW4F1c90LSJo0dBSSvjMaKCAKM=";
    };
    start = "true";
    date = "2025-04-27";
  };
  markview = {
    pname = "markview";
    version = "6bbbbf5790cdea622b53fe94b49b9801037e2db9";
    src = fetchFromGitHub {
      owner = "OXY2DEV";
      repo = "markview.nvim";
      rev = "6bbbbf5790cdea622b53fe94b49b9801037e2db9";
      fetchSubmodules = false;
      sha256 = "sha256-2/XB9QRHFrbzk+MlFVCfQsMv8F26MI4YN+9TkS7o2dQ=";
    };
    date = "2025-04-26";
  };
  mini-surround = {
    pname = "mini-surround";
    version = "5aab42fcdcf31fa010f012771eda5631c077840a";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.surround";
      rev = "5aab42fcdcf31fa010f012771eda5631c077840a";
      fetchSubmodules = false;
      sha256 = "sha256-fsJf1wOLPLSjAgGcjrckwrK1qkpyPjKHMeqEj589XkM=";
    };
    date = "2025-04-01";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "3409dc920d40bec4c901c0a122a80bee03d6d1e1";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "3409dc920d40bec4c901c0a122a80bee03d6d1e1";
      fetchSubmodules = false;
      sha256 = "sha256-k2akj/s6qJx/sCnz3UNHo5zbENTpw+OPuo2WPF1W7rg=";
    };
    date = "2025-03-07";
  };
  none-ls = {
    pname = "none-ls";
    version = "78546696d365c4d958351881ff43a8d82ac1ed44";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "78546696d365c4d958351881ff43a8d82ac1ed44";
      fetchSubmodules = false;
      sha256 = "sha256-C/kaKUJu+4OSoZefqtDl1pFwkMufUArdiETlXlPCusI=";
    };
    date = "2025-04-30";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "517df88cf2afb36652830df2c655df2da416a0ae";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "517df88cf2afb36652830df2c655df2da416a0ae";
      fetchSubmodules = false;
      sha256 = "sha256-yOPUgqHe0WT437aX8kp0P/reNgjZUNNRG7hvDgaeXT0=";
    };
    date = "2025-03-01";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "94d0fec9135719e046903bbbbf8f39e3d3436d4e";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "94d0fec9135719e046903bbbbf8f39e3d3436d4e";
      fetchSubmodules = false;
      sha256 = "sha256-V8qxiPdJMCbI3wMnT9sA37w5v+1BsW2o6/c6e5u66/I=";
    };
    date = "2025-04-30";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "d0a8c17c4dc721b00bc2ac305c6ffbb036beeb74";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "d0a8c17c4dc721b00bc2ac305c6ffbb036beeb74";
      fetchSubmodules = false;
      sha256 = "sha256-7L1rww1Z6NfcaOV5LUjspfwDhOk0asii8DdHmTe3ulc=";
    };
    date = "2025-04-30";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "b5825cf9ee881dd8e43309c93374ed5b87b7a896";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "b5825cf9ee881dd8e43309c93374ed5b87b7a896";
      fetchSubmodules = false;
      sha256 = "sha256-m4dQ8KuMhbEpRh6zLTlIUDN9ojFj69LZnXXLepmdFI8=";
    };
    date = "2025-04-13";
  };
  nvim-tree = {
    pname = "nvim-tree";
    version = "582ae48c9e43d2bcd55dfcc8e2e7a1f29065d924";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "582ae48c9e43d2bcd55dfcc8e2e7a1f29065d924";
      fetchSubmodules = false;
      sha256 = "sha256-RKgNmKWd6ARlmqCSjTZXhdaA9efkG/DfpndXgguh6vY=";
    };
    date = "2025-04-26";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "50b5b06bff13a9b4eab946de7c7033649a6618a1";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "50b5b06bff13a9b4eab946de7c7033649a6618a1";
      fetchSubmodules = false;
      sha256 = "sha256-ZjWpjOE531whPIFMs8z8BDOjTb4nkD6omJ9y6TXjWcs=";
    };
    date = "2025-04-25";
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "e0b72752d697142a7140bbf76a7905e7071d224c";
    src = fetchFromGitHub {
      owner = "obsidian-nvim";
      repo = "obsidian.nvim";
      rev = "e0b72752d697142a7140bbf76a7905e7071d224c";
      fetchSubmodules = false;
      sha256 = "sha256-P/9KGxEKnNeYoknDOGUcSl5cX+fWKjNXlkn9CJi6gjg=";
    };
    date = "2025-04-28";
  };
  plenary = {
    pname = "plenary";
    version = "857c5ac632080dba10aae49dba902ce3abf91b35";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "857c5ac632080dba10aae49dba902ce3abf91b35";
      fetchSubmodules = false;
      sha256 = "sha256-8FV5RjF7QbDmQOQynpK7uRKONKbPRYbOPugf9ZxNvUs=";
    };
    start = "true";
    date = "2025-02-11";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "63169f3c63896e1286ffdfe06642cab55eaa6b3c";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "63169f3c63896e1286ffdfe06642cab55eaa6b3c";
      fetchSubmodules = false;
      sha256 = "sha256-80zbogGoR1prFo0rHZEme3ILsBOJM9YcJkerylxDGEk=";
    };
    date = "2025-03-11";
  };
  quill-nvim = {
    pname = "quill-nvim";
    version = "08103ea02643a93065fe7dbc4ed22275719fc338";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "quill.nvim";
      rev = "08103ea02643a93065fe7dbc4ed22275719fc338";
      fetchSubmodules = false;
      sha256 = "sha256-SDMoqQwY3cKj5c5wHFdE+G0ZWVIeLjF6DU67tfDfi8w=";
    };
    date = "2024-12-10";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "55ad4fb76ab68460f700599b7449385f0c4e858e";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "55ad4fb76ab68460f700599b7449385f0c4e858e";
      fetchSubmodules = false;
      sha256 = "sha256-EeJvGtBwZgR7i9PEnGe4NTRiDQCgVKkSh5t8Xy5EYfE=";
    };
    date = "2025-04-16";
  };
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "3f2b7a94b7fa3c0f301dfa9644c94b543000efc2";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "3f2b7a94b7fa3c0f301dfa9644c94b543000efc2";
      fetchSubmodules = false;
      sha256 = "sha256-xf8GEAmq4l5OhzdcveTwPhVO25gp0tfP2H7S50c1ffg=";
    };
    date = "2025-04-27";
  };
  sayama-nvim = {
    pname = "sayama-nvim";
    version = "39175a766dfc80324d3130d27c3e7922f826226e";
    src = fetchFromGitHub {
      owner = "comfysage";
      repo = "sayama.nvim";
      rev = "39175a766dfc80324d3130d27c3e7922f826226e";
      fetchSubmodules = false;
      sha256 = "sha256-Rxjg6RvcN5JOP5CTv7Jj7AQJv36zRMaHiFEwhiBVgfw=";
    };
    date = "2024-05-30";
  };
  schemastore = {
    pname = "schemastore";
    version = "442901b78dca4da1078b32e25e1afb32460e0082";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "442901b78dca4da1078b32e25e1afb32460e0082";
      fetchSubmodules = false;
      sha256 = "sha256-YkCyGTROmQOa5gG7jkpMhYD6Upqx5HsiBI/1h+IOR68=";
    };
    date = "2025-04-24";
  };
  snacks-nvim = {
    pname = "snacks-nvim";
    version = "bc0630e43be5699bb94dadc302c0d21615421d93";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      fetchSubmodules = false;
      sha256 = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
    date = "2025-03-01";
  };
  telescope = {
    pname = "telescope";
    version = "a4ed82509cecc56df1c7138920a1aeaf246c0ac5";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "a4ed82509cecc56df1c7138920a1aeaf246c0ac5";
      fetchSubmodules = false;
      sha256 = "sha256-GF1zOHZItVZm3bx2wqI4hPj7EXQJ2F9KS4MtaEt2gm0=";
    };
    date = "2025-03-18";
  };
  telescope-project = {
    pname = "telescope-project";
    version = "8e11df94419e444601c09828dadf70890484e443";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "8e11df94419e444601c09828dadf70890484e443";
      fetchSubmodules = false;
      sha256 = "sha256-RyrfT/uQmuer+WN9Q58InTkuFJO+VQvVsp0ZRpRp7PQ=";
    };
    date = "2025-04-23";
  };
  telescope-ui-select = {
    pname = "telescope-ui-select";
    version = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "6e51d7da30bd139a6950adf2a47fda6df9fa06d2";
      fetchSubmodules = false;
      sha256 = "sha256-YRhNmmG4gx9Ht8JwjQfbTjJyTHEuZmtP6lqnhOsk8bE=";
    };
    date = "2023-12-04";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "304a8d204ee787d2544d8bc23cd38d2f929e7cc5";
      fetchSubmodules = false;
      sha256 = "sha256-at9OSBtQqyiDdxKdNn2x6z4k8xrDD90sACKEK7uKNUM=";
    };
    date = "2025-01-14";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "9a88eae817ef395952e08650b3283726786fb5fb";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "9a88eae817ef395952e08650b3283726786fb5fb";
      fetchSubmodules = false;
      sha256 = "sha256-fytbX+L12TK45YKFU9K+iFJcDrwboKabihc2LtX29J4=";
    };
    date = "2025-03-09";
  };
  trouble = {
    pname = "trouble";
    version = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "85bedb7eb7fa331a2ccbecb9202d8abba64d37b3";
      fetchSubmodules = false;
      sha256 = "sha256-au9wp88a0CutEf2f8Bi0vFTUR0zvQKgFX1vMVg4myGI=";
    };
    date = "2025-02-12";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "3c501d7c7f79457932a8750a2a1476a004c5c1a9";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "3c501d7c7f79457932a8750a2a1476a004c5c1a9";
      fetchSubmodules = false;
      sha256 = "sha256-roSEM3YGfKIoGQIlvaC0IFCIzkPLhJmnUMc+CBQmQE8=";
    };
    date = "2025-04-25";
  };
  undotree = {
    pname = "undotree";
    version = "eab459ab87dd249617b5f7187bb69e614a083047";
    src = fetchFromGitHub {
      owner = "jiaoshijie";
      repo = "undotree";
      rev = "eab459ab87dd249617b5f7187bb69e614a083047";
      fetchSubmodules = false;
      sha256 = "sha256-FIYDyfkaIS9C16ClWKLMdpSPv/OrcOalVVsyFJBU2eI=";
    };
    date = "2024-02-09";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "4a745ea72fa93bb15dd077109afbb3d1809383f2";
      fetchSubmodules = false;
      sha256 = "sha256-1AteNwnc7lCHLIwM8Ejm2T9VTIDM+CeAfvAUeSQRFKE=";
    };
    date = "2025-02-19";
  };
  wakatime = {
    pname = "wakatime";
    version = "e46d7c4f98ee0f40782008dd60cb2a79c377fb1d";
    src = fetchFromGitHub {
      owner = "wakatime";
      repo = "vim-wakatime";
      rev = "e46d7c4f98ee0f40782008dd60cb2a79c377fb1d";
      fetchSubmodules = false;
      sha256 = "sha256-/Sgmj3LaodArqkIcAmxbNtBdqO5qQX9fU4fvANR+Ies=";
    };
    date = "2025-01-25";
  };
}
